# Generated by Django 3.1.7 on 2021-03-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sigthings',
            new_name='Sighting',
        ),
    ]
