# Generated by Django 3.1.7 on 2021-04-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20210325_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(blank=True, help_text='Adult or Juvenile', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='shift',
            field=models.CharField(help_text='AM or PM', max_length=5),
        ),
    ]
